-- =====================================================================
-- V1 - Tabla de usuarios del sistema (réplica de app/models/users.py)
-- Esquema: fitnation   |   base: tempsensor
--
-- IMPORTANTE: los identificadores van entre COMILLAS DOBLES.
-- En Flask/SQLAlchemy las columnas camelCase se emiten entrecomilladas,
-- así que en producción se llaman exactamente "idUser" y "passwordUser".
-- Sin comillas PostgreSQL las pasaría a minúsculas (iduser/passworduser)
-- y el mapeo dejaría de coincidir con el modelo original.
-- =====================================================================

CREATE TABLE fitnation.users (
    "idUser"       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre"       VARCHAR(80)   NOT NULL,
    "email"        VARCHAR(120)  NOT NULL,
    "passwordUser" VARCHAR(255)  NOT NULL,
    "rol"          VARCHAR(20)   NOT NULL DEFAULT 'usuario',
    "telefono"     VARCHAR(20),
    "creado_en"    TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota'),
    CONSTRAINT uq_users_nombre UNIQUE ("nombre"),
    CONSTRAINT uq_users_email  UNIQUE ("email"),
    CONSTRAINT ck_users_rol CHECK ("rol" IN ('admin', 'recepcionista', 'entrenador', 'usuario'))
);

CREATE INDEX ix_users_rol ON fitnation.users ("rol");

COMMENT ON TABLE  fitnation.users               IS 'Usuarios del sistema (equivale a la tabla users de Flask)';
COMMENT ON COLUMN fitnation.users."passwordUser" IS 'Hash de la contrasena. En Flask esta columna se llama passwordUser';
COMMENT ON COLUMN fitnation.users."rol"          IS 'admin | recepcionista | entrenador | usuario';
