-- =====================================================================
-- V2 - Tablas del gimnasio (réplica de app/models/*.py de Flask)
-- Esquema: fitnation   |   base: tempsensor
--
-- Regla de comillas (igual que V1 y que SQLAlchemy): solo se entrecomillan
-- los identificadores con MAYÚSCULAS ("idCliente", "nombrePlan"...).
-- Los minúsculos (dia_semana, metodo_pago, user_id...) van sin comillas.
-- =====================================================================

-- ---------------------------------------------------------------- clientes
CREATE TABLE fitnation.clientes (
    "idCliente" INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre"    VARCHAR(100) NOT NULL,
    "edad"      INTEGER      NOT NULL,
    "telefono"  VARCHAR(20),
    "email"     VARCHAR(120)
);
COMMENT ON TABLE fitnation.clientes IS 'Clientes del gimnasio (equivale a la tabla clientes de Flask)';

-- ------------------------------------------------------------------ planes
CREATE TABLE fitnation.planes (
    "idPlan"         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombrePlan"     VARCHAR(100) NOT NULL,
    "precio"         DOUBLE PRECISION NOT NULL,
    "duracionMeses"  INTEGER      NOT NULL
);
COMMENT ON TABLE fitnation.planes IS 'Planes de membresía (equivale a la tabla planes de Flask)';

-- ---------------------------------------------------------------- horarios
CREATE TABLE fitnation.horarios (
    "idHorario"  INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idUser"     INTEGER     NOT NULL REFERENCES fitnation.users("idUser"),
    dia_semana   VARCHAR(20) NOT NULL,
    hora_inicio  VARCHAR(10) NOT NULL,
    hora_fin     VARCHAR(10) NOT NULL
);
CREATE INDEX ix_horarios_idUser ON fitnation.horarios ("idUser");
COMMENT ON TABLE fitnation.horarios IS 'Horarios de entrenadores (idUser = entrenador, equivale a horarios de Flask)';

-- ------------------------------------------------- user_horarios (N:M)
CREATE TABLE fitnation.user_horarios (
    user_id    INTEGER NOT NULL REFERENCES fitnation.users("idUser") ON DELETE CASCADE,
    horario_id INTEGER NOT NULL REFERENCES fitnation.horarios("idHorario") ON DELETE CASCADE,
    CONSTRAINT pk_user_horarios PRIMARY KEY (user_id, horario_id)
);
COMMENT ON TABLE fitnation.user_horarios IS 'Usuarios inscritos en cada horario (tabla user_horarios de Flask)';

-- ------------------------------------------------------------ inscripciones
CREATE TABLE fitnation.inscripciones (
    "idInscripcion" INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fecha"         TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota'),
    "idCliente"     INTEGER   NOT NULL REFERENCES fitnation.clientes("idCliente"),
    "idPlan"        INTEGER   NOT NULL REFERENCES fitnation.planes("idPlan")
);
CREATE INDEX ix_inscripciones_cliente ON fitnation.inscripciones ("idCliente");
CREATE INDEX ix_inscripciones_plan    ON fitnation.inscripciones ("idPlan");
COMMENT ON TABLE fitnation.inscripciones IS 'Inscripciones cliente<->plan (equivale a inscripciones de Flask)';

-- ------------------------------------------------------------------- pagos
CREATE TABLE fitnation.pagos (
    "idPago"         INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "monto"          DOUBLE PRECISION NOT NULL,
    "fecha"          TIMESTAMP        NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota'),
    metodo_pago      VARCHAR(50)      NOT NULL DEFAULT 'Efectivo',
    "idCliente"      INTEGER          NOT NULL REFERENCES fitnation.clientes("idCliente"),
    "idInscripcion"  INTEGER          REFERENCES fitnation.inscripciones("idInscripcion")
);
CREATE INDEX ix_pagos_cliente      ON fitnation.pagos ("idCliente");
CREATE INDEX ix_pagos_inscripcion  ON fitnation.pagos ("idInscripcion");
COMMENT ON TABLE fitnation.pagos IS 'Pagos de clientes (equivale a pagos de Flask)';

-- ------------------------------------------------- asistencias_entrenadores
CREATE TABLE fitnation.asistencias_entrenadores (
    "idAsistencia" INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idHorario"    INTEGER   NOT NULL REFERENCES fitnation.horarios("idHorario"),
    "idUser"       INTEGER   NOT NULL REFERENCES fitnation.users("idUser"),
    "fecha"        DATE      NOT NULL DEFAULT ((now() AT TIME ZONE 'America/Bogota')::date),
    hora_entrada   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota'),
    hora_salida    TIMESTAMP,
    observaciones  TEXT
);
CREATE INDEX ix_asist_entrenador_user    ON fitnation.asistencias_entrenadores ("idUser");
CREATE INDEX ix_asist_entrenador_horario ON fitnation.asistencias_entrenadores ("idHorario");
COMMENT ON TABLE fitnation.asistencias_entrenadores IS 'Asistencia de entrenadores (equivale a asistencias_entrenadores de Flask)';

-- ----------------------------------------------------- asistencias_clientes
CREATE TABLE fitnation.asistencias_clientes (
    "idAsistencia" INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idUser"       INTEGER   NOT NULL REFERENCES fitnation.users("idUser"),
    "fecha"        DATE      NOT NULL DEFAULT ((now() AT TIME ZONE 'America/Bogota')::date),
    hora_entrada   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota'),
    hora_salida    TIMESTAMP,
    observaciones  TEXT
);
CREATE INDEX ix_asist_cliente_user ON fitnation.asistencias_clientes ("idUser");
COMMENT ON TABLE fitnation.asistencias_clientes IS 'Asistencia de clientes al gym (equivale a asistencias_clientes de Flask)';
